version: "3.3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - 8080:8080
  api:
    image: iksde-bank-server:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    command: ./manage.py runserver 0.0.0.0:8000
    entrypoint: ./wait-for-postgres.sh
    volumes:
      - .:/code
      - log_data:/var/log/
      - tmp_data:/tmp
    ports:
      - 8000:8000
    env_file:
      - ./config.env
    depends_on:
      - postgres
      - redis
      - celery
      - beat
  celery:
    image: iksde-bank-server:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    volumes:
      - .:/code
    command: celery -A iksde_bank worker -l info
    env_file:
      - ./config.env
    depends_on:
      - postgres
      - redis
  celery-transfers:
    image: iksde-bank-server:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    volumes:
      - .:/code
    command: celery -A iksde_bank worker -l info -Q transfers
    env_file:
      - ./config.env
    depends_on:
      - postgres
      - redis
  beat:
    image: iksde-bank-server:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    volumes:
      - .:/code
    command: celery -A iksde_bank beat -l INFO
    env_file:
      - ./config.env
    depends_on:
      - celery
      - postgres
      - redis
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
  redis:
    image: redis:5.0-alpine
    volumes:
      - redis_data:/data/
    ports:
      - 6379:6379

volumes:
  log_data:
  tmp_data:
  postgres_data:
  redis_data:
  keycloak_data:
